docs/dev-docs/modules/ROOT/pages/index.adoc
Update the index page of Developer Documentation
=> update dev-docs start_page

docs/dev-docs/modules/publishing/pages/source-code-hosting.adoc
Tried to use `table` within an `iframe` to show data table.
=> Debug Source Code Hosting page data table not showing data issue

docs/dev-docs/modules/publishing/pages/source-code-hosting.adoc, package-lock.json, package.json
Clean up jenkins-docs Source Code Hosting page.
=> Move permissions-table logic away from jenkins-docs

docs/dev-docs/modules/publishing/pages/source-code-hosting.adoc
Added tested code to try and render data in Source Code Hosting data table.
=> Try functional code tested independently for Source Code Hosting data table

docs/tutorials/modules/ROOT/pages/build-a-java-app-with-maven.adoc
I am undoing the changes we have tried previously @Vandit1604
=> Revert changes

docs/tutorials/modules/ROOT/pages/build-a-java-app-with-maven.adoc, docs/tutorials/modules/ROOT/pages/build-a-node-js-and-react-app-with-npm.adoc
See revised page-aliaes @Vandit1604
=> Rework redirection page-aliases

docs/tutorials/modules/ROOT/pages/build-a-java-app-with-maven.adoc, docs/tutorials/modules/ROOT/pages/tutorial-for-installing-jenkins-on-IBM-Cloud.adoc
We missed one page to delete and page-aliases on build a project with maven using jenkins
@krisstern
=> chore: Clean up

docs/user-docs/antora.yml, docs/user-docs/modules/ROOT/pages/index.adoc
=> Revert after Presentation

docs/events/antora.yml, docs/events/modules/fosdem/nav.adoc, docs/events/modules/fosdem/pages/archive/2021.adoc, docs/events/modules/fosdem/pages/index.adoc, docs/events/modules/hacktoberfest/pages/faq.adoc, docs/events/modules/hacktoberfest/pages/index.adoc
Many links are not working in this section, I'll fix them later.
=> Fix: Events Section

docs/events/modules/ROOT/pages/index.adoc
Hard code the data for the Major Events section on Jenkins Event page to check if the visual effects can be retained.
=> Hard code to test if Major Events section can be implemented

docs/events/modules/ROOT/pages/index.adoc
Try adding CSS styling to Major Events section for individual events.
=> Add CSS styling to Major Events section

docs/events/modules/ROOT/pages/index.adoc, package-lock.json, package.json
Add missing timezone in set calendar function to see if calendar will show.
=> Add missing timezone in set calendar function

package-lock.json, package.json
=> Add `bootstrap` with npm

docs/events/modules/ROOT/pages/index.adoc
=> Add missing JQuery library

heading-script.py
Added the Strapi and Gatsby Integration for Blogs 
ref: https://strapi.io/blog/build-a-static-blog-with-gatsby-and-strapi
=> Add new strapi gatsby blog code

blog/src/css/download.module.css, blog/src/pages/download.js
Couldn't find the same icon so used another icon which i got after searching for Library
=> Add Jenkins download sources table in download page

docs/user-docs/modules/scaling/pages/architecting-for-manageability.adoc, docs/user-docs/modules/scaling/pages/architecting-for-scale.adoc, docs/user-docs/modules/scaling/pages/scaling-jenkins-on-kubernetes.adoc, docs/user-docs/modules/system-administration/pages/backing-up.adoc, docs/user-docs/modules/system-administration/pages/diagnosing-errors.adoc, docs/user-docs/modules/system-administration/pages/monitoring.adoc, docs/user-docs/modules/system-administration/pages/systemd-services.adoc, docs/user-docs/modules/system-administration/pages/viewing-logs.adoc, docs/user-docs/modules/troubleshooting/pages/diagnosing-errors.adoc
=> Remove section heading from backup docs

docs/community/modules/chat/pages/index.adoc, docs/dev-docs/antora.yml, docs/dev-docs/modules/FIPS-140/nav.adoc, docs/dev-docs/modules/FIPS-140/pages/index.adoc, docs/projects/modules/infrastructure/pages/index.adoc, docs/user-docs/modules/ROOT/nav.adoc, docs/user-docs/modules/installing-jenkins/nav.adoc, docs/user-docs/modules/platform-information/nav.adoc, ui/src/layouts/wip.hbs, ui/src/partials/banner.hbs, ui/src/partials/wip-article.hbs, ui/src/partials/wip-body.hbs, ui/src/partials/wip-main.hbs
adding `:page-layout: wip` to the top of a page will add the WIP banner like we have on https://www.jenkins.io/doc/developer/views/ 
Added banner looks like this
=> Add Banner and WIP Banner

docs/security/modules/ROOT/pages/advisories/index.adoc
Comment out unsused code in passthrough code block.
=> Fix: patch issues with advisories setup 2

MAINTAINERS.adoc
Add the guide to versioning the documentation. Currently named it `MAINTAINERS.adoc` it can be changed though.
=> Add MAINTAINERS.adoc 

site/content/2023/08/28/2023-08-28-number-of-open-issues-probe.adoc, site/gatsby-config.js, site/gatsby-node.js, site/src/components/RecentBlogPosts.js, site/src/css/blogpost.module.css, site/src/templates/blog-list-template.js
There is dummy text in the blog listing for each blog. I have replaced it with a blog teaser under each blog.
=> Add blog teaser and change URL for blogposts to be `/blog/*`
